# Generated by Django 5.2.6 on 2025-09-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('time_password', models.CharField(max_length=5)),
                ('is_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='user',
            new_name='phone',
        ),
    ]
