# Generated by Django 5.2.6 on 2025-09-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_phonemassage_rename_user_todolist_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='phone',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='username',
        ),
    ]
